### ISSUE TITLE
Photos Framework

### ISSUE THREAD

**Issue by mythodeia** [mariohahn/MHVideoPhotoGallery#98]
do you have it in your plans to make this work with the Photos Framework as well?
thanks

**Comment by stefanocomba** [comment]
+1

**Comment by mythodeia** [comment]
@mariohahn any updates on this? are you planning on making in the future another gallery to work with photos framework or update this one with the latest bells and whistles?

**Comment by stefanomondino** [comment]
+1 (and thank you for this great library!)

**Comment by jayjayesh** [comment]
+1  for this nice library, 
      any plan to support PHAssets?

**Comment by mblyk** [comment]
+

**Comment by fruitcoder** [comment]
I'm about to use the library and I always try to use the `localIdentifier` of `PHAssets`/`PHObject`s to reference the assets without having them in memory completely or having to store them in an extra directory just to assure the fileURL is valid in the future. I'll try to add the `localIdentifier` to the `MHGalleryItem` so that clients can hand the `localIdentifier` of the asset and the library will take care of fetching the correct image/video from the users photo library.
